### ISSUE TITLE
Ошибка запуска nginx при установке

### ISSUE THREAD

**Issue by rybushkindmitry** [sip3io/sip3-ansible#5]
При установке не запускается nginx по причине "a duplicate default server for 0.0.0.0:80 in /etc/nginx/nginx.conf:39"
Скорее всего проблема связана с тем, что дефолтный конфиг меняется позже, чем выполняется запуск nginx

**Comment by agafox** [comment]
Thank you for the report. This bug was fixed in the following commit: https://github.com/sip3io/sip3-ansible/commit/24960ce94e01b40031d9d9eacace09afc35d0550
